namespace DocGen.DocIO.DLS;

public enum OleObjectType
{
	Undefined,
	AdobeAcrobatDocument,
	BitmapImage,
	MediaClip,
	Equation,
	GraphChart,
	Excel_97_2003_Worksheet,
	ExcelBinaryWorksheet,
	ExcelChart,
	ExcelMacroWorksheet,
	ExcelWorksheet,
	PowerPoint_97_2003_Presentation,
	PowerPoint_97_2003_Slide,
	PowerPointMacroPresentation,
	PowerPointMacroSlide,
	PowerPointPresentation,
	PowerPointSlide,
	Word_97_2003_Document,
	WordDocument,
	WordMacroDocument,
	VisioDrawing,
	MIDISequence,
	OpenDocumentPresentation,
	OpenDocumentSpreadsheet,
	OpenDocumentText,
	OpenOfficeSpreadsheet1_1,
	OpenOfficeText_1_1,
	Package,
	VideoClip,
	WaveSound,
	WordPadDocument,
	OpenOfficeSpreadsheet,
	OpenOfficeText
}
