namespace DocGen.Pdf.Native;

internal enum GDI_CHARSET
{
	ANSI_CHARSET = 0,
	DEFAULT_CHARSET = 1,
	SYMBOL_CHARSET = 2,
	SHIFTJIS_CHARSET = 128,
	EASTEUROPE_CHARSET = 238,
	RUSSIAN_CHARSET = 204,
	MAC_CHARSET = 77
}
