namespace DocGen.Pdf.Native;

internal enum StringInfoCtype2 : ushort
{
	C2_LEFTTORIGHT = 1,
	C2_RIGHTTOLEFT = 2,
	C2_EUROPENUMBER = 3,
	C2_EUROPESEPARATOR = 4,
	C2_EUROPETERMINATOR = 5,
	C2_ARABICNUMBER = 6,
	C2_COMMONSEPARATOR = 7,
	C2_BLOCKSEPARATOR = 8,
	C2_SEGMENTSEPARATOR = 9,
	C2_WHITESPACE = 10,
	C2_OTHERNEUTRAL = 11,
	C2_NOTAPPLICABLE = 0
}
