using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyCopyright("Copyright © 2001-2024 DocGen Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: InternalsVisibleTo("DocGen.HtmlConverter.Portable")]
[assembly: InternalsVisibleTo("DocGen.DocIORenderer.Portable")]
[assembly: InternalsVisibleTo("DocGen.XlsIORenderer.Portable")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.Android")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.UWP")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.iOS")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms")]
[assembly: InternalsVisibleTo("DocGen.Report.Portable")]
[assembly: InternalsVisibleTo("DocGen.EJ.ReportViewer_Core")]
[assembly: InternalsVisibleTo("DocGen.PresentationRenderer.Portable")]
[assembly: InternalsVisibleTo("PDF.Tests_Portable_Base")]
[assembly: InternalsVisibleTo("PDF.ManualTests_Base")]
[assembly: InternalsVisibleTo("PDF.ManualTests_Portable_Base")]
[assembly: InternalsVisibleTo("DocGen.EJ2.PdfViewer")]
[assembly: InternalsVisibleTo("DocGen.PdfViewer.AspNet.Core")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.AspNet.Core")]
[assembly: InternalsVisibleTo("DocGen.Pdf.Imaging.Portable")]
[assembly: InternalsVisibleTo("DocGen.XpsToPdfConverter.Portable")]
[assembly: InternalsVisibleTo("BoldReports.Web")]
[assembly: InternalsVisibleTo("DocToPDFConverter.Tests_Base_Portable")]
[assembly: InternalsVisibleTo("BoldSign.DocumentManipulator")]
[assembly: InternalsVisibleTo("DocGen.OCRProcessor.Portable")]
[assembly: InternalsVisibleTo("OCR.Tests_Portable_Base")]
[assembly: InternalsVisibleTo("DocGen.GridConverter.WPF")]
[assembly: InternalsVisibleTo("NUnit_OnTimeIssues_PPTX_Portable")]
[assembly: AssemblyDelaySign(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyCompany("DocGen Inc.")]
[assembly: AssemblyConfiguration("Release-Xml")]
[assembly: AssemblyFileVersion("26.2.9")]
[assembly: AssemblyInformationalVersion("26.2.9")]
[assembly: AssemblyProduct("DocGen.PDF.Portable.Portable (LR)")]
[assembly: AssemblyTitle("DocGen.Pdf.Portable")]
[assembly: AssemblyVersion("26.2.9.0")]
