using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyCopyright("Copyright © 2001-2024 DocGen Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: InternalsVisibleTo("DocGen.OCRProcessor.Portable")]
[assembly: InternalsVisibleTo("DocGen.Pdf.Imaging.Portable")]
[assembly: InternalsVisibleTo("DocGen.Pdf.Portable")]
[assembly: InternalsVisibleTo("DocGen.DocIO.Portable")]
[assembly: InternalsVisibleTo("DocGen.XlsIO.Portable")]
[assembly: InternalsVisibleTo("DocGen.OfficeChart.Portable")]
[assembly: InternalsVisibleTo("DocGen.Presentation.Portable")]
[assembly: InternalsVisibleTo("DocGen.PresentationRenderer.Portable")]
[assembly: InternalsVisibleTo("DocGen.DocIORenderer.Portable")]
[assembly: InternalsVisibleTo("DocGen.ExcelChartToImageConverter.Portable")]
[assembly: InternalsVisibleTo("DocGen.OfficeChartToImageConverter.Portable")]
[assembly: InternalsVisibleTo("DocGen.XlsIORenderer.Portable")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.Android")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.UWP")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms.iOS")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.XForms")]
[assembly: InternalsVisibleTo("DocGen.SkiaSharpHelper.Portable")]
[assembly: InternalsVisibleTo("DocGen.EJ2.PdfViewer")]
[assembly: InternalsVisibleTo("DocGen.PdfViewer.AspNet.Core")]
[assembly: InternalsVisibleTo("DocGen.SfPdfViewer.AspNet.Core")]
[assembly: InternalsVisibleTo("DocGen.XpsToPdfConverter.Portable")]
[assembly: InternalsVisibleTo("DocGen.EJ2.DocumentEditor")]
[assembly: InternalsVisibleTo("DocGen.WordProcessor.AspNet.Core")]
[assembly: InternalsVisibleTo("DocGen.SfRichTextBoxAdv.WPF")]
[assembly: InternalsVisibleTo("DocGen.GridConverter.WPF")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyName("")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyCompany("DocGen Inc.")]
[assembly: AssemblyConfiguration("Release-Xml")]
[assembly: AssemblyFileVersion("26.2.9")]
[assembly: AssemblyInformationalVersion("26.2.9")]
[assembly: AssemblyProduct("DocGen.Compression.Portable.Portable (LR)")]
[assembly: AssemblyTitle("DocGen.Compression.Portable")]
[assembly: AssemblyVersion("26.2.9.0")]
